name: infinity_sweeper
description: Infinity Sweeper.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.3+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  auto_size_text: ^3.0.0
  easy_splash_screen: ^1.0.3
  flutter_svg: ^1.0.0
  flutter_neumorphic: ^3.2.0
  clay_containers: ^0.3.2
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: "^0.9.2"
  shared_preferences: ^2.0.11
  fl_chart: ^0.40.6
  google_mobile_ads: ^1.0.1
  intl: ^0.17.0
  purchases_flutter: ^3.9.4
  games_services: ^2.0.7
  carousel_slider: ^4.0.0
  
flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/icon.png"
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: any
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons_tutorial/
  fonts:
    - family: Futura Round
      fonts:
        - asset: assets/fonts/FuturaRound.ttf
        - asset: assets/fonts/FuturaRoundBold.ttf